services:
  backend:
    container_name: backend
    image: alflyingwhale/qr-code-generator-backend:1.0
    volumes:
      - ./qr-code-generator-backend/logs:/var/server/logs
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - PORT=${BACKEND_PORT}
      - CACHE_EXPIRATION_TIME=${CACHE_EXPIRATION_TIME}
      - MAX_CACHE_SIZE=${MAX_CACHE_SIZE}
    env_file:
      - .env

  frontend:
    container_name: frontend
    image: alflyingwhale/qr-code-generator-frontend:1.0
    ports:
      - "${VITE_APP_PORT}:${VITE_APP_PORT}"
    environment:
      - VITE_APP_PORT=${VITE_APP_PORT}
      - VITE_API_URL=${VITE_API_URL}
    env_file:
      - .env