services:
  qr-code-generator-backend:
    build: ./qr-code-generator-backend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - CACHE_EXPIRATION_TIME=3600
      - MAX_CACHE_SIZE=100
    env_file:
      - ./qr-code-generator-backend/.env
    networks:
      - app-network

  qr-code-generator-frontend:
    build: ./qr-code-generator-frontend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    env_file:
      - ./qr-code-generator-frontend/.env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge