services:
  backend:
    container_name: backend
    build: ./qr-code-generator-backend
    volumes:
      - ./qr-code-generator-backend/logs:/var/server/logs
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - CACHE_EXPIRATION_TIME=3600
      - MAX_CACHE_SIZE=100
    env_file:
      - ./qr-code-generator-backend/.env
    # networks:
    #   - backend

  frontend:
    container_name: frontend
    build: ./qr-code-generator-frontend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    env_file:
      - ./qr-code-generator-frontend/.env
    # networks:
    #   - backend

  # nginx:
  #   image: nginx:1.27.0-alpine
  #   ports:
  #     - "8080:80" # Expose Nginx on port 8080 for the backend
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf # Mount Nginx configuration file
  #   networks:
  #     - backend

# networks:
#   backend:
#     driver: bridge