apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    app: qrserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: qrserver
  template:
    metadata:
      labels:
        app: qrserver
    spec:
      containers:
      - name: qrserver
        image: alflyingwhale/qr-code-generator-backend:1.0
        ports:
        - containerPort: 8080
        env:
        - name: "PORT"
          valueFrom:
            secretKeyRef:
              name: server-secret
              key: server-port
        - name: "CACHE_EXPIRATION_TIME"
          valueFrom:
            secretKeyRef:
              name: server-secret
              key: cache-expiration-time
        - name: "MAX_CACHE_SIZE"
          valueFrom:
            secretKeyRef:
              name: server-secret
              key: max-cache-size

---

apiVersion: v1
kind: Service
metadata:
  name: qrserver-service
spec:
  selector:
    app: qrserver
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080