apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: alflyingwhale/qr-code-generator-frontend:1.1
        ports:
        - containerPort: 3000
        env:
        - name: "VITE_APP_PORT"
          valueFrom:
            secretKeyRef:
              name: webapp-secret
              key: vite-app-port
        - name: "VITE_API_URL"
          valueFrom:
            configMapKeyRef:
              name: server-config
              key: server-url

---

apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30100